# Generated by Django 3.1.6 on 2021-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField()),
            ],
            options={
                'db_table': 'discount_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('companies_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discount_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalDiscountTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_percent', models.BooleanField(default=False)),
                ('is_total', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'discount_external_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwProductPricing',
            fields=[
                ('product_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_gst_fees', models.CharField(max_length=10)),
                ('sw_product_fees', models.FloatField(blank=True, null=True)),
                ('sw_product_gst_fees', models.CharField(max_length=10)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sw_product_pricing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwProductPricingExternal',
            fields=[
                ('product_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_gst_fees', models.CharField(max_length=10)),
                ('sw_product_fees', models.FloatField(blank=True, null=True)),
                ('sw_product_gst_fees', models.CharField(max_length=10)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sw_product_pricing_external',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwProductsTbl',
            fields=[
                ('product_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sw_products_tbl',
                'managed': False,
            },
        ),
    ]
